# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # Testing
  desc "Runs all the unit tests"
  lane :unit_tests do
    run_tests(workspace: "FileImportApp.xcworkspace",
  	      scheme: "FileImportAppTests",
	      device: "iPhone 14",
  	      clean: false)
  end

  desc "Runs all the UI tests"
  lane :ui_tests do
    run_tests(workspace: "FileImportApp.xcworkspace",
  	      scheme: "FileImportAppUITests",
              devices: ["iPhone 14", "iPad Air (5th generation)"],
  	      clean: false)
  end

end
