name: Run Tests

on:
  pull_request:
    branches: [ main ]
      
jobs:
  run_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Bundle dependencies
        run: bundle install

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
           ${{ runner.os }}-pods-

      - name: CocoaPods dependencies
        run: bundle exec pod install
      
      - name: Run Unit Tests
        run: bundle exec fastlane unit_tests

      - name: Run UI Tests
        run: bundle exec fastlane ui_tests
